### ISSUE TITLE
a variety of issues in the list

### ISSUE THREAD

**Issue by ultsppi** [MineralFish/mineralfish.github.io#4]
there's a few oversites in the site that i can't fix because you forgot to give me editing privileges (probably). 

- gold nugget fish's role is "quote chains", when it should be "false quoting"
- new copper fish, new iron fish, new golden fish, newer copper fish, newer iron fish, and newer golden fish are not included. these fish only appeared once in posts in the main minecraft topic before the mineral fish topic even existed, so i get why they were missed
- here are links to them: https://u.cubeupload.com/UlsPPi/newcopperfish.png https://u.cubeupload.com/UlsPPi/newironfish.png  https://u.cubeupload.com/UlsPPi/newgoldenfish.png https://u.cubeupload.com/UlsPPi/newercopperfish.png https://u.cubeupload.com/UlsPPi/newerironfish.png  https://u.cubeupload.com/UlsPPi/newergoldenfish.png 
- i was the creator of marc92020 fish
- debbie the chicken fish is not included (this may be a good thing)
- prismarine shard fish (https://u.cubeupload.com/UlsPPi/prismarineshardfish.png) is not included, because i literally made it just now

**Comment by CST1229** [comment]
gave you owner rank in the org
hopefully you can edit now

**Comment by CST1229** [comment]
and also yes i'll be fixing them sometime

> debbie the chicken fish is not included (this may be a good thing)

intentional

**Comment by CST1229** [comment]
resolved in 1.1.0 and 1.1.1, except for:
- new golden fish (your url returned a 404)
- debbie fish (because intentional)
